EXTRA_CFLAGS = \
    -g \
    -Wall \
    -Wno-error=unused-variable \
    -Wno-error=unused-function \
    -I./linux_source_tree.ignore/include/ \
    -I$(MOD_SOURCE_DIR)/include/ \
    -DDEBUG \
    -DBUILDING_AS_MODULE \

obj-m += kyttie.o
kyttie-y := \
    cp.o \
    proto.o \
    sock.o \
    ix/sock.o \
